# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26eec0fd09883781b695b6f88bfb00b9bff903eb8107b2f812c1d9b195625ce8dc7c48ba407683ae60940dcba0257cc0f2d21ae7e1c948bd9f22407d8df969d1

test:
  secret_key_base: 5ddf6530dc9d135c01f8a4f482346b4d5fbfabd67f5e80b7fd961df371496bde4a0794db98387b6fbeb6bb01e2fb65eb0fdca810eb334a0c969b91288c9fc527

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
